export const FETCH_PROGRESS_REQUEST = "FETCH_PROGRESS_REQUEST";
export const FETCH_PROGRESS_SUCCESS = "FETCH_PROGRESS_SUCCESS";
export const FETCH_PROGRESS_ERROR = "FETCH_PROGRESS_ERROR";

export const MARK_VIDEO_WATCHED_REQUEST = "MARK_VIDEO_WATCHED_REQUEST";
export const MARK_VIDEO_WATCHED_SUCCESS = "MARK_VIDEO_WATCHED_SUCCESS";
export const MARK_VIDEO_WATCHED_ERROR = "MARK_VIDEO_WATCHED_ERROR";
