sonar.organization=nahn-th
sonar.projectKey=Nahn-th_ci-cd-pipelines

# 2. Thông tin hiển thị trên giao diện SonarCloud
sonar.projectName=DevOps CI-CD Pipelines E-Learning
sonar.projectVersion=1.0.0

# 3. Đường dẫn quét code chính
sonar.sources=backend,frontend/src
sonar.sourceEncoding=UTF-8

# 4. Loại trừ các file rác, file build không cần quét lỗi
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.js,**/*.spec.js,frontend/src/setupTests.js

# 5. Cấu hình quét file Test
sonar.tests=backend,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.jsx

# 6. Đường dẫn đọc kết quả Unit Test (Cực kỳ quan trọng để chấm điểm Coverage)
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
